# Generated by Django 3.2.7 on 2021-10-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainuser', '0002_auto_20211014_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='special',
            field=models.BooleanField(default=False),
        ),
    ]
