# Generated by Django 3.2.7 on 2021-10-15 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainuser', '0004_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Cart',
        ),
    ]
