# Generated by Django 3.2.7 on 2021-10-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainuser', '0008_auto_20211015_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
